import type { Metadata } from "next";
import "./globals.css";
import { Press_Start_2P } from "next/font/google";
import Starfield from "./components/Starfield";
import TreeNavbar from "./components/TreeNavbar";
import CrystalDock from "./components/CrystalDock";
import ScrollProgress from "./components/ScrollProgress";

const pixelFont = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pixel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`
          ${pixelFont.variable}
          antialiased bg-background text-foreground overflow-x-hidden
        `}
      >
        <Starfield />
        {/* <TreeNavbar /> */}
        <CrystalDock />
        <ScrollProgress />
        {children}
      </body>
    </html>
  );
}
